server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
    
spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: country-rest-api
          uri: http://country-rest-api/countries
          predicates:
            - Path=/api/country/**
          filters:
            - StripPrefix=2

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    country-rest-api: /country/**
---

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
